/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Home
 */
public class JFrmEagPrincipal extends javax.swing.JFrame {
    

    /**
     * Creates new form JFrmEagPrincipal
     */
      public JFrmEagPrincipal() {
        initComponents();
        setTitle("Sistema de vendas de Maquiagem");
        setExtendedState(MAXIMIZED_BOTH);
    }
      public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new JFrmEagPrincipal().setVisible(true);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jMenuBar1 = new javax.swing.JMenuBar();
        JMnuCadastro = new javax.swing.JMenu();
        jMnuClientes = new javax.swing.JMenuItem();
        jMnuFornecedores = new javax.swing.JMenuItem();
        jMProdutos = new javax.swing.JMenuItem();
        jMnuUsuarios = new javax.swing.JMenuItem();
        jMVendedor = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMnuSair = new javax.swing.JMenuItem();
        JMnuMovimentos = new javax.swing.JMenu();
        jMnuCompras = new javax.swing.JMenuItem();
        jMnuVendas = new javax.swing.JMenuItem();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JMnuCadastro.setMnemonic('C');
        JMnuCadastro.setText("Cadastros");

        jMnuClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cliente.png"))); // NOI18N
        jMnuClientes.setMnemonic('C');
        jMnuClientes.setText("Clientes");
        jMnuClientes.addActionListener(this::jMnuClientesActionPerformed);
        JMnuCadastro.add(jMnuClientes);

        jMnuFornecedores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-fornecedor-24.png"))); // NOI18N
        jMnuFornecedores.setMnemonic('F');
        jMnuFornecedores.setText("Fornecedor");
        jMnuFornecedores.addActionListener(this::jMnuFornecedoresActionPerformed);
        JMnuCadastro.add(jMnuFornecedores);

        jMProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-produtos-24.png"))); // NOI18N
        jMProdutos.setMnemonic('P');
        jMProdutos.setText("Produtos");
        jMProdutos.addActionListener(this::jMProdutosActionPerformed);
        JMnuCadastro.add(jMProdutos);

        jMnuUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-usuário-24.png"))); // NOI18N
        jMnuUsuarios.setMnemonic('U');
        jMnuUsuarios.setText("Usuarios");
        jMnuUsuarios.addActionListener(this::jMnuUsuariosActionPerformed);
        JMnuCadastro.add(jMnuUsuarios);

        jMVendedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-vendedor-24.png"))); // NOI18N
        jMVendedor.setMnemonic('V');
        jMVendedor.setText("Vendedor");
        jMVendedor.addActionListener(this::jMVendedorActionPerformed);
        JMnuCadastro.add(jMVendedor);
        JMnuCadastro.add(jSeparator1);

        jMnuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit.png"))); // NOI18N
        jMnuSair.setMnemonic('S');
        jMnuSair.setText("Sair");
        jMnuSair.addActionListener(this::jMnuSairActionPerformed);
        JMnuCadastro.add(jMnuSair);

        jMenuBar1.add(JMnuCadastro);

        JMnuMovimentos.setMnemonic('M');
        JMnuMovimentos.setText("Movimentos");

        jMnuCompras.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuCompras.setMnemonic('C');
        jMnuCompras.setText("Compras");
        JMnuMovimentos.add(jMnuCompras);

        jMnuVendas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuVendas.setMnemonic('V');
        jMnuVendas.setText("Vendas");
        JMnuMovimentos.add(jMnuVendas);

        jMenuBar1.add(JMnuMovimentos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMnuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuClientesActionPerformed
   JDlgEagClientes jDlgEagClientes = new JDlgEagClientes(null, true);
        jDlgEagClientes.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMnuClientesActionPerformed

    private void jMnuFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuFornecedoresActionPerformed
 JDlgEagFornecedores jDlgEagFornecedores = new JDlgEagFornecedores(null, true);
        jDlgEagFornecedores.setVisible(true);      // TODO add your handling code here:
    }//GEN-LAST:event_jMnuFornecedoresActionPerformed

    private void jMProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMProdutosActionPerformed
  JDlgEagProdutos jDlgEagProdutos = new JDlgEagProdutos(null, true);
        jDlgEagProdutos.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMProdutosActionPerformed

    private void jMnuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuUsuariosActionPerformed
JDlgEagUsuarios jDlgEagUsuarios = new JDlgEagUsuarios(null, true);
        jDlgEagUsuarios.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMnuUsuariosActionPerformed

    private void jMVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMVendedorActionPerformed
   JDlgEagVendedor jDlgEagVendedor = new JDlgEagVendedor(null, true);
        jDlgEagVendedor.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMVendedorActionPerformed

    private void jMnuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuSairActionPerformed
 System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jMnuSairActionPerformed

    /**
     * @param args the command line arguments
     */

                                      

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JMnuCadastro;
    private javax.swing.JMenu JMnuMovimentos;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JMenuItem jMProdutos;
    private javax.swing.JMenuItem jMVendedor;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMnuClientes;
    private javax.swing.JMenuItem jMnuCompras;
    private javax.swing.JMenuItem jMnuFornecedores;
    private javax.swing.JMenuItem jMnuSair;
    private javax.swing.JMenuItem jMnuUsuarios;
    private javax.swing.JMenuItem jMnuVendas;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
